# Generated by Django 4.1.5 on 2023-06-23 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_resume_remove_home_shortdescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='fromDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='toDate',
            field=models.DateField(null=True),
        ),
    ]
