# Generated by Django 4.1.5 on 2023-06-23 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_resume_fromdate_resume_todate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='briefDescription',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='bottomDescription',
            new_name='description',
        ),
        migrations.AddField(
            model_name='resume',
            name='calender',
            field=models.CharField(blank=True, choices=[('1', 'E.C.'), ('2', 'G.C.')], default='2', help_text='Which callender is selected', max_length=1, null=True),
        ),
    ]
