# Generated by Django 4.1.5 on 2023-06-23 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_rename_briefdescription_resume_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='image',
            field=models.ImageField(help_text='my Image', null=True, upload_to='myImage'),
        ),
    ]
