# Generated by Django 4.1.5 on 2023-06-24 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_alter_portifolio_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='portifolio',
            name='technologies',
            field=models.TextField(blank=True, help_text='List the technologies used for this project separating with ,', max_length=20000, null=True),
        ),
    ]
