# Generated by Django 4.1.5 on 2023-06-24 08:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_portifolio_technologies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='contactPhone',
            field=models.CharField(help_text='My Phone Number', max_length=60, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: 251-000000000 eg:251-906625917', regex='^(251-)\\d{9}$')]),
        ),
    ]
