# Generated by Django 4.1.5 on 2023-06-26 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_rename_linkdinlink_home_linkdinlink_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Active'), ('0', 'In Active')], default='1', help_text='Is Active', max_length=1, null=True, unique=True),
        ),
    ]
