# Generated by Django 4.1.5 on 2023-06-26 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_alter_home_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='freelance',
            field=models.CharField(blank=True, choices=[('1', 'Available'), ('0', 'Not Available')], default='0', help_text='Status to show if I am available for freelance or not', max_length=1, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Active'), ('0', 'In Active')], default='0', help_text='status to tell if the service is active or not', max_length=1, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Active'), ('0', 'In Active')], default='0', max_length=1, null=True, unique=True),
        ),
    ]
