# Generated by Django 4.1.5 on 2023-06-29 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0011_alter_about_freelance_alter_contact_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='status',
        ),
        migrations.AlterField(
            model_name='skillcategory',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Active'), ('0', 'In Active')], default='1', help_text='status to show if the skill category is active and vissible to the website or not', max_length=1, null=True),
        ),
    ]
