# Generated by Django 4.1.5 on 2023-06-29 13:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0012_remove_feedback_status_alter_skillcategory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='phone',
            field=models.CharField(help_text='The phone number of the person who sent the feedback', max_length=60, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: 251-000000000 eg:251-906625917', regex='^(251-)\\d{9}$')]),
        ),
    ]
